public class IF_ELSE{
    public static void main(String[] args) {
        System.out.println("Hello World");
        int x = 10;
        int y = 5;

        // Boolean condition
        if (x > y) {
            System.out.println("x is greater than y");
        } else {
            System.out.println("x is not greater than y");
        }
        int u = 6;
        String name = "True";
        if (u > 10){
            System.out.println(name);
        } else {
            System.out.println("False");
        }
    }
}